#Server Details
server:
  port: 80

#Postgres Database configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

#Data JPA details
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      
#Mail server details    
  mail:
    host: smtp.gmail.com
    port: 587
    username: skullknife07@gmail.com
    password: Ckumar1996
    properties:
     mail:
      smtp:
       starttls:
         enable: true

#MasterAcount Config
master:
 user:
  name: CHANDAN
  email: nckr2014@gmail.com
      
    
