server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health
    username: root
    password: password
    
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      
#Mail server details    
  mail:
    host: smtp.gmail.com
    port: 587
    username: skullknife07@gmail.com
    password: Ckumar1996
    properties:
     mail:
      smtp:
       starttls:
         enable: true
     
master:
 user:
  name: NIT-Chandan
  email: nckr2014@gmail.com
      
    
